name: efs-to-s3 Deploy master branch

on:
  push:
    paths:
      - "efs-to-s3/**"
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Upload to ECR
        working-directory: ./efs-to-s3
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b6g9t8f1  
          docker build -t efs-to-s3 .
          docker tag efs-to-s3:latest public.ecr.aws/b6g9t8f1/efs-to-s3:latest
          docker push public.ecr.aws/b6g9t8f1/efs-to-s3:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
