name: inputs-to-s3 Deploy master branch

on:
  push:
    paths:
      - "inputs-to-s3/**"
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Upload to ECR
        working-directory: ./inputs-to-s3
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i8i  
          docker build -t inputs-to-s3 .
          docker tag inputs-to-s3:latest public.ecr.aws/i8i/inputs-to-s3:latest
          docker push public.ecr.aws/i8i/inputs-to-s3:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
