name: kaniko-executor-ecr Deploy master branch

on:
  push:
    paths:
      - "kaniko-executor-ecr/**"
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Upload to ECR
        working-directory: ./kaniko-executor-ecr
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i8i  
          docker build -t kaniko-executor-ecr .
          docker tag kaniko-executor-ecr:latest public.ecr.aws/i8i/kaniko-executor-ecr:latest
          docker push public.ecr.aws/i8i/kaniko-executor-ecr:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
